### ISSUE TITLE
[BUG] Information window activates Play - caused by flatten seasons

### ISSUE THREAD

**Issue by TechXXX** [umbrellaplug/umbrellaplug.github.io#163] opened 2022-12-30 18:12 UTC
### Bug

Information window activates Play - caused by flatten seasons

https://www.youtube.com/watch?v=A7cBlfioQR8

### Expected Result

normal info screen opening

### Steps To Reproduce

https://www.youtube.com/watch?v=A7cBlfioQR8

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment] 2022-12-30 23:56
Looked into this a bit and it's a much tougher bug to resolve than you'd expect. This is caused by the url assigned to items in itemlist when they are added. When they are added if flatten seasons is enabled all items are added as episodes vs without flatten season they are added as a tvshow which triggers different actions and methods in the router. I'll look into a little more and see if I can track it down, but it's not a high priority bug as it's not stopping the addon from working. I do understand you don't want it to do this and it would annoy me also so I'll see what I can do. I want to be honest though if it ends up being a large amount of work I'm not sure if it's worth the effort.

**Comment by TechXXX** [comment] 2022-12-31 09:35
Ok, let's hope it's fixable without too much work. This basically renders the 'information dialogue' inoperable, any help will be appreciated.

**Comment by umbrellaplug** [comment] 2022-12-31 14:16
> Ok, let's hope it's fixable without too much work. This basically renders the 'information dialogue' inoperable, any help will be appreciated.

No, it renders the information dialogue inoperable with that combination of settings. I could easily not be helpful here and close this issue out and just say "don't use those combination of settings" but I'm trying to help. If you read the changelog from months ago AH2 in particular is not supported. The skin is a beta skin and is changed often. I have wasted more than one weekend of my time looking at changes for something a skin developer has changed on a whim. I'm still not convinced any of this is worth the effort when the fix is to turn a setting off, but even with that thought I'm still going to look into it.

**Comment by TechXXX** [comment] 2022-12-31 14:58
"If you read the changelog from months ago AH2 in particular is not supported." I have read that changelog and appreciate anything you can do to remedy this. If not, no big deal either, I appreciate you making accommodations in your addon to different skins and understand you can't accommodate every and everyones settings and skins. AH2 is a very popular skin and it's great to you're not dismissing its bugs outright.

**Comment by xyzfre** [comment] 2022-12-31 17:50
I agree AH2 seems to be getting very popular and always being developed,, it's truly a great skin and Umbrella only gets better and better💯 so the combination would be flawlessly ,,I also thank you as well for not dismissing the bugs

**Comment by TechXXX** [comment] 2023-01-01 12:26
Happy new year, couldn't agree more. Umbrella with AH2 has improved so much over the last year it's amazing. By the way. not sure what changed about the progress section in My tv shows (umbrella) but I was checking something for someone else and I stumbled upon it. Progress within Umbrella is episode view, but as a widget it shows TV shows....just the way I like it! I got rid of all flatten seasons settings and it runs without problems now. 

Here's progress from within Umbrella:

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/10571873/210170378-d26f7df5-5417-410a-8f22-d80044b27d44.png">


And as a widget it shows tv shows vs Episode view, excellent: 

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/10571873/210170484-b89ccafd-3f47-48ce-9ddd-ac63510dad82.png">


Works for me. Thanks for everything, keep up the good work in the new year.

**Comment by umbrellaplug** [comment] 2023-01-01 13:49
Good news. I will keep that in mind in case that comes up again.

The change for progress was for durations. Runtimes/ duration were being added at the seasonal level and overwriting the times with minutes and ah2 needed seconds for durations to show correctly.

**Closed** 2023-02-11 16:46 UTC
Labels: bug
