### ISSUE TITLE
[BUG] TV Shows not Playing Plex

### ISSUE THREAD

**Issue by phri-warec** [umbrellaplug/umbrellaplug.github.io#397] opened 2024-08-07 15:34 UTC
### Bug

Bug

hello!
umbrella-plugin plays movies without problems but not a single episode of a tv series from my plex server.

the checked series and episode are available.

i get the following error message in the log; "playlist player: skipping unplayable item." 

I have now tried the problem with different variants.
No matter if I use Libreelec 10, 11, 12 on my Rpi 4 or Libreelec 12 leagacy on my HTPC.
I just can't manage to solve the problem. 

### Expected Result

At best, an episode of a series starts the same way as the films.

### Steps To Reproduce

0. On RPI 4
1.  Flash Libreelec 
2. Start and Install Libreelec
3. Install Umbrella by Repo
4. Add Plex Share 
5. Set Plex Share activ
6. Open Umbrella
7. Try Movie to see it works
8. Try TV Show and cry

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

https://paste.kodi.tv/yikulehelo 
Libreelec 10, RPi4 Umbrella 6.6.64
Kodi Logfile Uploader
My Plexshare is mainly for non-English content

### Checklist

- [X] I have included logs and the version of Kodi I am using..
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment] 2024-08-07 15:39
This is a duplicate of an issue already opened. You cannot use default behavior "show information" and enable continuous playback at the same time currently in Umbrella. You will need to either change your default play method back to play, turn off continuous playback, or wait for a possible fix. Closing this issue as a duplicate.

#396

**Closed by umbrellaplug** 2024-08-07 15:40 UTC
Labels: bug

**Comment by phri-warec** [comment] 2024-08-07 21:39
Thank you very much for the quick reply!
I'm a bit lost, what exactly do you mean by "change your default play method **back** to play"? I haven't changed anything.
What exactly do you mean by "turn off continuous playback"?

Are you talking about libreelec settings or umbrella addon settings?

So the problem has nothing to do with whether you are using kodi version 19 20 or 21?

I'm really sorry, but I don't quite understand you.

**Comment by phri-warec** [comment] 2024-08-08 18:59
- I set umbrella Plug: Playback: Continue off; Auto Resume off
- > no change TV Shows no stream found (playlist player skipping)
-  where can i find the "show information" setting?

**Comment by umbrellaplug** [comment] 2024-08-08 21:25
Can you please try the latest version of umbrella on the test repo (6.6.654) and please go to Kodi > Settings > Videos > Play next video automatically and make sure nothing is selected? It's likely set to episodes now.

https://umbrellakodi.github.io

**Comment by phri-warec** [comment] 2024-08-09 15:36
So
Flashed Rpi with Libreelec 12 = Kodi 21
Installed Kodi Log
Installed Umbrella
Set Umbrella Debug Log
Gone to Kodi Settings/Player/Videos Play next video automatically everything is already deselected checked with uncategorised
Linked Plex in Umbrella
Enabled manually Plexshare
Movies work
No success https://paste.kodi.tv/qoyahovewo

**Comment by umbrellaplug** [comment] 2024-08-09 19:24
Are you getting results for tv shows when you scrape your plex server?

**Comment by phri-warec** [comment] 2024-08-09 20:50
pm4k worked normal.
Online browser  app.plex.tv/  worked
Composite (A Plex client) mostly also did not work but some shows worked to continue
how can i check how  tv shows are scraped?

**Comment by umbrellaplug** [comment] 2024-08-09 21:52
This is what I was asking. When you search a show are you getting any results for tv shows or are you seeing "no results" on every tv show? I'm able to see my plex server as a result when I scrape for shows and I can source select that as a source.

**Comment by umbrellaplug** [comment] 2024-08-09 22:06
https://github.com/user-attachments/assets/7d6159aa-8dce-4af2-a723-708777069e5b

Here's an example video of what plex results will look like in the source select window. If you're not getting results there your plex server is not returning the episodes when a query for those episodes are sent to it. You may want to check your metadata on the plex server and make sure the episodes are labeled correctly.

**Comment by phri-warec** [comment] 2024-08-10 05:54
I think you're on to something.
Deadpool worked in umbrellaplug perfectly because Englishname = Germanname .
On the otherhand "Der König der Löwen"1994 (the lion king) which is on my plex, is not found / not found like in the video you send me.
Same Issue with the lion king 2019.
At the moment, everything in Libreelec and Umbrella is set to English. Does it change anything in the handling of Meta if I change the location settings there?
--
Thank you very much. I really appreciate your help.
