### ISSUE TITLE
[BUG] Trakt Finish Watching for TV Shows Not Scraping/Resolving

### ISSUE THREAD

**Issue by rtuRgALp** [umbrellaplug/umbrellaplug.github.io#95] opened 2022-10-08 17:31 UTC
Hello,

I’m having issues playing titles from my “Finish Watching” folder under “My TV Shows” (Trakt). 

These titles play flawlessly from the nested “Progress” folder. But when trying to play an uncached title from “Finish Watching”, playback fails and I get a “no streams found” error. 

I’ve tried deauthorizing and reauthorizing Trakt, clearing all cache, and forcing a local Trakt sync but all to no avail. 

One thing I noticed is that the episode metadata seems to be pulled into content in that folder incorrectly. In this example, the episode I was trying to watch was stated as 1 minute long. All the other episodes had no duration information. This is not present in the “Progress” folders. 

https://paste.kodi.tv/wequwetana 
https://paste.kodi.tv/ubafuhilar

**Comment by umbrellaplug** [comment] 2022-10-08 18:47
I need more details to resolve this. From your log it appears you're using a skin and tmdbhelper. Can you give me exact steps to reproduce the issue including any details like "i'm using a this skin, setup this way"? Is this happening only on one show or all shows from Finish Watching?

I just tried it on my system running no skin and I went to Umbrella>My TV Shows> Finish Watching. I click on an episode there and I clicked "View Uncached Torrents" and selected one and it attempted to download the file to my cloud as expected. 

It looks like it tried to call the native "onPlaybackError" code in kodi from your logs which is an indication of a bad download or file.

**Comment by rtuRgALp** [comment] 2022-10-09 01:44
I was using using Arctic Horizon 2 by jurialmunkey as my main skin. But I just tried again with no skin and I am still having the same issue.

In AH2, I added the Finish Watching folder as a widget to my Home Screen and whenever I attempt to play an episode there that I haven’t played before on a fresh Kodi install, it doesn’t work. The scrapers gets zero results and the content does not load. 

It will only work from that widget if I play it from the Progress folder first. Then it picks up the provider cache previously generated. 

I am having this issue from the add-on itself too. 

Note: I am on tvOS 16.1 running Kodi Matrix 19.4.

**Comment by umbrellaplug** [comment] 2022-10-09 04:49
I'm not getting the same results. Please provide exact steps to reproduce the error.

**Comment by rtuRgALp** [comment] 2022-10-10 23:42
1. Install tvOS on Apple TV via Xcode (non-jailbroken method)
2. download umbrella 
3. authorize trakt
4. authorize debrid service
5. force trakt sync
6. navigate to tv shows >  finish watching
7. observe missing duration metadata 
8. select show to play
9. observe no available streams error

**Comment by rtuRgALp** [comment] 2022-10-10 23:44
I think this is specific to the tvOS implementation of Kodi - I'm not sure how to emulate this, but I am happy to help you procure an Apple TV for testing purposes. Please let me know if there is a way for me to donate to sponsor this effort.

**Comment by umbrellaplug** [comment] 2022-10-11 01:55
I don't do any type of donations or anything like that. Thanks though. I will see if I can duplicate this behavior on my device. I will need to dig around for my apple tv, it's been a couple of years since I left the jailbreak scene. I still have my developer license though so I should be able to sideload. I'll find the exact show you're having issues with from your logs and see what I can find. What debrid services do you use so I can try to match my results to yours?

**Comment by rtuRgALp** [comment] 2022-10-11 02:25
Ok, sounds good. I use Real-Debrid. Thanks for looking into it!

**Comment by rtuRgALp** [comment] 2022-10-12 05:07
Just tried again to make sure I’m not going crazy and it is indeed still happening. For whatever reason, that Finish Watching folder doesn’t get sources scraped unless I’ve first played the content from another folder (like Progress). 

A head scratcher indeed.

**Comment by umbrellaplug** [comment] 2022-10-12 23:38
I haven't had a chance to look into this yet, but I will. I'm in the middle of a pretty significant enhancement to the plugin. Once I get that completed I will look into this. I didn't want you to think I wasn't looking at it or forgot.

**Comment by rtuRgALp** [comment] 2022-10-13 01:13
All good! I know you have other priorities for the add-on. Thanks for the update.

**Comment by umbrellaplug** [comment] 2022-10-16 04:45
Should be fixed in the latest update.

**Closed by umbrellaplug** 2022-10-16 04:45 UTC

**Comment by rtuRgALp** [comment] 2022-10-16 13:52
Nice! I’ll give it a try and see.
