### ISSUE TITLE
Scrapping and source select 

### ISSUE THREAD

**Issue by Alex20090313** [umbrellaplug/umbrellaplug.github.io#165] opened 2022-12-30 19:23 UTC
After I scrape it takes long for source select to come up, I'm using a Apple TV 4K 2022 128gb and after the latest update, every time I click on a show and it scrapes it try to get the source it does not pop up right away like it use to prior to the update now it takes time, it may take 5 min to pop up and sometimes after it pops up and you click on the show it will pop up while watching the show and when you back out it will display a source error

https://vimeo.com/785272506

https://paste.kodi.tv/uromuzupos

Please find the logs and a short video I made of the issue 

Thank you

**Comment by umbrellaplug** [comment] 2022-12-30 21:22
Thanks for the logs! It appears the full-screen scrape is causing you issues. I've been seeing some issues with this on my side as well and I'm working on an update to fix it. Can you please change your settings for scrape to background or foreground or icon only and let me know if it makes any difference?

**Comment by Alex20090313** [comment] 2022-12-30 21:27
I have tried both as you mention on Reddit, it does the same exact thing it loads but then takes forever to get the source select page to come up, did you want me to do another log for you?

**Comment by umbrellaplug** [comment] 2022-12-30 21:29
Thanks, the other thing I can think of would be the source select. Does this happen when set to autoplay instead of source select?

**Comment by adamosborne83** [comment] 2022-12-30 21:30
> I have tried both as you mention on Reddit, it does the same exact thing it loads but then takes forever to get the source select page to come up, did you want me to do another log for you? 

Try auto play..... does it then load into the TV show/movie..... just process of elimination.

**Comment by Alex20090313** [comment] 2022-12-30 22:28
I shall try auto play, last I tried it worked only issue is due to the high internet I have at home I want always the biggest file to play at high res, that's why I put sources select so I can pick and choose the stream I want to also meet the sound system and tv needs

**Comment by umbrellaplug** [comment] 2022-12-30 22:47
Totally understand, I'm just trying to understand which component may be causing you this issue. Your logs didn't have a whole lot in them to help unfortunately. If you could just try that and let me know if it's any faster that will tell me what to look at.

**Comment by Alex20090313** [comment] 2022-12-31 00:37
I would definitely like to help, what would you like me to test out and log so you may see the issue

**Comment by umbrellaplug** [comment] 2022-12-31 02:26
Can you please change your logging settings in the addon for Debugging> Log Level - Extra Info >Logging Location > Kodi.log?

I just posted a new version on the test repo. You're welcomed to try that one and let me know if it makes a difference. The test repo can be added by adding `https://umbrellaplug.github.io/umbrellatest` as a source and loading version 6.6.02.

Let me know if you get a chance to try that out and your results.

**Comment by Alex20090313** [comment] 2022-12-31 04:18
Sorry for the late reply, I tried the new test file and it still does the same thing after it scrapped for shows it takes 3-4 minutes before the source select comes up

https://paste.kodi.tv/iraquxoyeg

Here is the log file

Hope it helps

**Comment by umbrellaplug** [comment] 2022-12-31 05:14
Strange. I'm not getting the same delay. I'm not really seeing it in the log either. Can you clear your provider cache?

**Comment by umbrellaplug** [comment] 2022-12-31 13:33
I'm trying to find an apple tv so I can attempt to duplicate this issue but honestly these things are expensive and not great.

**Comment by Alex20090313** [comment] 2022-12-31 13:41
I'm going to try to clear the cache shortly, honestly I know there expensive the Apple TVs but out of all the streaming boxes I've tried this one is the one for me that always comes out on top between features and usability and being already in the Apple ecosystem helps

**Comment by Alex20090313** [comment] 2022-12-31 14:16
This is the video on the Apple TV if you can see once the scrapping is done how long it takes to open the source select 

https://vimeo.com/785405426

This is the video on my MacBook once it's done scrapping how it opens right away the source list 

https://vimeo.com/785406116

This is the log from the Apple TV 

https://paste.kodi.tv/fuzoholeke

This is the log from the MacBook 

https://paste.kodi.tv/bepibukuvi

Maybe there might be something different

**Comment by umbrellaplug** [comment] 2022-12-31 14:29
Totally understand, don't take my comment about your device as a dig. I use apple stuff as well, the TV is just the one thing I avoided. When I left the jailbreak scene years ago I didn't feel like messing with it due to being such a pain. Now I think you guys are just sideloading these days.  I'm looking around to see if I can find a used Apple TV or a deal on one. If I can get my hands on the device I can try to see what's causing the difference. My suspicion is the python version, but it's a guess without one. I do some errors in your log for the apple tv for my settings files. I'll see if I can figure anything out on that. It looks like something is breaking in the clean_settings function. I cannot imagine that's causing you issues, but if it cannot read your settings file that might be part of the delay your seeing there as it's having trouble getting the colors from the settings file.

**Comment by Alex20090313** [comment] 2022-12-31 14:40
I thought I was going crazy lol I'm happy you were able to find a error on the log files, wow you go back to the jailbreak days I miss those good old days now it's getting so hard to open up iOS, we will see what will happen in 2024 with the new eu law wanting apple to allow 3rd party App Store on there devices, thank you for all your help

**Comment by umbrellaplug** [comment] 2022-12-31 15:12
It looks like you might be having an error with the settings file. When you update umbrella one of the things it does is check your settings file and looks like you're not making it through that. Luckily I recently added something for that. 
Can you please try Tools > Fix Blank Settings: UMBRELLA from the menu. This will require you to re-add trakt and debrid (i'm sorry). I think your issue is related to that settings file. This should delete the file for you and reload the addon so it's re-created.

**Comment by Alex20090313** [comment] 2022-12-31 15:18
I shall definitely try this, I believe I already did yesterday I'll try again tho and log it

**Comment by umbrellaplug** [comment] 2022-12-31 16:08
> I shall definitely try this, I believe I already did yesterday I'll try again tho and log it

Thanks, sorry for all the back and forth. I'm particularly interested in this line from your log.

`[2022-12-31 09:01:11] [ plugin.video.umbrella: ERROR ]: From func name: /resources/lib/modules/clean_settings.py.clean_settings() Line # :39`

That is triggered by the update code in the main router of the addon. Something is failing there. That's why I asked about deleting that settings.xml file. Your log shows a failure with that again this time too.

```
[2022-12-31 09:01:11] [ plugin.video.umbrella: ERROR ]: From func name: /resources/lib/modules/clean_settings.py.clean_settings() Line # :39
                       msg : FileNotFoundError -> [Errno 2] No such file or directory: '/private/var/mobile/Containers/Data/Application/529915D0-9A95-4755-A0E1-141AD9D8E671/Library/Caches/Kodi/userdata/addon_data/plugin.video.umbrella/settings.xml'
```

Here's where it gets to bad news. I believe this is a larger problem with Element Tree in the version of python they have used in 19.5 and version 20 of kodi. There's an ongoing thread with Jurial (skin developer, tmdbhelper developer) as well where he has been fighting crashes like crazy for a while now with kodi 20. It looks like this is causing your issues. I'd be very interested to see the version of python on that kodi 19.5 build on the apple tv versus your mac. Is your mac 19.5 also? I'm not sure if the problem exists on the mac version. The whole time I've been working on this update I would have been on 19.4, to make it worse the problem isn't seen on Windows so I would have never seen it in my lab. I have multiple devices here that I have not upgraded to 19.5 yet due to it dropping right before I released this update.

I really don't like to lose though so I was thinking of possible workarounds for you. I can think of 3 possible ways that might fix this for you.

1. Try to manually delete the settings file. You can actually go to your Kodi > Settings > File Manager. Hit Profile directory> addon_data> plugin.video.umbrella > settings.xml and delete that file. Restarting kodi after doing that should rebuild the settings file.

2. Remove and Fresh Install Umbrella (including removing settings) - This is tedious, but likely would put a fresh settings.xml file in for you and resolve the problem for now.

3. This is not an option you're going to like, but this is your best option. I would downgrade to kodi 19.4 till they fixed this. I say this, because element tree is used in a lot of addons. It's a core component of parsing xml files with python.

**Comment by Alex20090313** [comment] 2022-12-31 16:16
Wow thank you for the detailed reply, no worries about the back and forth I am always willing to assist such an amazing developer for an amazing add on I appreciate all of this man, I forgot to mention yes my Mac kodi version is on kodi 19.5 the lates build with the latest os update and the latest build number of umbrella and the problem does not happen on there I might have to downgrade back to kodi 19.4 that does not bother me but I'll try the first work around to see if it may help you as well, definitely an addon not only myself would like to keep but I'm sure everyone else would like to as well

**Comment by xyzfre** [comment] 2022-12-31 17:27
> This is not an option you're going to like, but this is your best option. I would downgrade to kodi 19.4 till they fixed this. I say this, because element tree is used in a lot of addons. It's a core component of parsing xml files with python.

@umbrellaplug if I created a back up with 19.5 is it safe to restore it on a fresh install of 19.4 really appreciate any feedback Umbrella is amazing 💯

**Comment by umbrellaplug** [comment] 2022-12-31 17:34
@xyzfre I don't see any reason that would cause you issues. The component in question is being used in the actual python library bundled in kodi so your backup shouldn't contain that. Are you also having issues? Are you also running an Apple TV? 

I've read the issue is showing up on Android devices also. I'm in the process of upgrading devices right now to see if I can duplicate it. Is the Apple TV running 32 or 64bit kodi?

**Comment by xyzfre** [comment] 2022-12-31 17:55
No my apologies I'm on Windows 11 Pro I just like to read all these post and learn from them,, Only issue I was having was with the cloud scraper but I see you have been addressing that ,, you truly are an AMAZING dev💯 you always communicate very well with us end users cause I know some of us can be annoying sometimes lol

**Comment by umbrellaplug** [comment] 2022-12-31 18:08
@xyzfre Just pushed version 6.6.02. That should fix your cloud scraper issue, but this is not the same thing. This has to do with being unable to parse the settings.xml file.

@Alex20090313 I've been looking around for Apple TV. I know your original comment said 2022, I just want to confirm. It looks like you have 3rd generation with ethernet is that correct?

**Comment by Alex20090313** [comment] 2022-12-31 18:15
Yes correct it's the new 2022 128gb with Ethernet

**Comment by umbrellaplug** [comment] 2022-12-31 20:56
Can you let me know if any of those workaround worked for you? I found an Apple TV near me, but I'd rather not buy one today if I don't need to.

**Comment by Alex20090313** [comment] 2022-12-31 21:32
Im only going to be able to try it out on Monday night I won't be home till then unfortunately I shall keep you posted on the results

**Comment by Alex20090313** [comment] 2023-01-01 16:43
Happy New years, sorry for the wait I was able to test the 3 solutions this morning option 1 and 2 both don't work they still cause the delay I logged it for you 

https://paste.kodi.tv/utehekacav

Also I tried the latest update 6.6.03 on my mac version of kodi and iOS version of kodi both on 19.5 and Nether the iOS version or Mac version have issues, only tv os 

The only option I have now is to downgrade back to 19.4 I'm looking on the kodi site for the 19.4 file since I deleted it on my computer but I no longer am able to find, I'm going to do some digging on the kodi site to try to find 19.4 if I can't find it I'm heading over to a buddy's house later that is still on 19.4 and I'll do the test from there tv to see if the lag happens on the 19.4 version of kodi on tvos with the latest 6.6.03 version of umbrella

**Comment by umbrellaplug** [comment] 2023-01-01 16:51
Do you mind trying out 6.6.03 on the apple tv? I spoke with TikiPeter last night and he had a similar issue a while back with Apple TV and it had to do with checking settings at startup and how they load on the apple tv. I added some code in last night to account for that. I can see in your logs you uploaded you actually were running 6.6.02.

**Comment by Alex20090313** [comment] 2023-01-01 16:58
I just downgraded back to kodi 19.4 on build 6.6.03 and the same issue is occurring 

https://paste.kodi.tv/xakejajowi

**Comment by umbrellaplug** [comment] 2023-01-01 17:04
> I just downgraded back to kodi 19.4 on build 6.6.03 and the same issue is occurring
> 
> https://paste.kodi.tv/xakejajowi

Those logs still stop at 6.6.02 and yesterday. Can you make sure you re-enabled logging after re-installing? I think I'm going to go get one of these apple tv's today.

**Comment by Alex20090313** [comment] 2023-01-01 17:08
My bad I did not know I had to enable logging every time here is the new log on 19.4 running version 6.6.03

https://paste.kodi.tv/ekeyucirez

**Comment by umbrellaplug** [comment] 2023-01-01 17:12
Thanks. I think accessing the settings when building the items for the source list could be potentially be causing your issue. I'm going to change the code to be called 1 time instead of each time an item is added. I'll let you know when I push 6.6.04 in a few to test repo.

**Comment by umbrellaplug** [comment] 2023-01-01 20:49
Alright, sorry for the delay. If you could when you get a chance please try version 6.6.04 from the test repo and let me know if there's an improvement please.

**Comment by umbrellaplug** [comment] 2023-01-02 20:25
@Alex20090313 Were you able to test this?

**Comment by Alex20090313** [comment] 2023-01-02 20:27
Will be testing it In about an hour sorry was working all day I'll let you know once I'm able to test it

**Comment by Alex20090313** [comment] 2023-01-02 21:52
I updated my Kodi back to 19.5 to test the new update 6.6.04 and I tested it it feels a lot snappier and it is working better then version 6.6.03 I'm sending you the log so you may see if there error is gone 

https://paste.kodi.tv/waxojanemi

**Comment by umbrellaplug** [comment] 2023-01-02 21:59
Sorry to keep asking, but just want to confirm. Source select is no longer taking an excessive amount of time?
Log looks great honestly. I will wait for your confirmation but I believe this issue is resolved in this version.

**Comment by Alex20090313** [comment] 2023-01-02 22:15
No worries I'm happy to keep helping and yes it works there is no more lag for the source select to come up, I'm going to be using the beta for the evening to make sure everything is running smoothly will update you later to let you know

**Comment by umbrellaplug** [comment] 2023-01-02 22:19
That is great news. I rewrote my code to load the data into that window using a more efficient method. Let me know if anything comes up. I appreciate the feedback. There's a few other fixes in that version and myself and another tester have been running it for about 2 days now so I will likely push that to the public side soon.

**Comment by umbrellaplug** [comment] 2023-01-04 15:06
Looking good. Let me know if you have anything come up.

**Closed by umbrellaplug** 2023-01-04 15:06 UTC
