### ISSUE TITLE
Umbrella won't play tv shows within the addon

### ISSUE THREAD

**Issue by alexp4re** [umbrellaplug/umbrellaplug.github.io#383] opened 2024-07-19 02:35 UTC
### Bug

hello. umbrella won't play tv shows within the addon, but will play it when the shows been integrated in the kodi library. movies are playing fine.

i am getting error in the log; "playlist player: skipping unplayable item." im not sure if i enable playnext feature in settings (disabled now) or it may be a recent update for umbrella that did listed playnext feature was changed.

i have spent countless hours & im at my wits end. internet search no luck. hopefully someone can help. thanks in advance. my first time posting on here, but excuse me if i did anything wrong.

kodi 21 omega, windows 10, umbrella 6.6.62, w/ RD, location: usa

update: just discovered, it plays by context menu; source select "play only this"

### Expected Result

to be able to play tv shows within the addon

### Steps To Reproduce

sorry no debug log. too advance & overwhelming for a senior like me.

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

kodi 21 omega, windows 10, umbrella 6.6.62, w/ RD, location: usa
![SNAG-0000](https://github.com/user-attachments/assets/c5aaf06b-0188-4efb-ba9f-5fb253df9d9f)

### Checklist

- [X] I have included logs and the version of Kodi I am using..
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment] 2024-07-19 04:25
This is a Kodi bug caused by setting the default actuon to info instead of play. There's nothing I can do to fix this. Kodi needs to fix the issue they created with their changes in Kodi 21.

**Comment by alexp4re** [comment] 2024-07-19 05:18
but i was on kodi for many months now. everything was fine. the problem occur recenrly though. am i the only on reporting this problem. everyone should be affected as well on a massive level. any suggestions or there's no fix?

**Comment by umbrellaplug** [comment] 2024-07-19 11:42
Kodi 21 broke info with playlists. Instead of sending the actual video file it sends video_ts/video_ts when using the info button. Playnext depends on playlists.

It works in Fen because he doesn't use playlist for play next. 

You should just switch to using fen instead of umbrella since it does what you're wanting.

**Comment by umbrellaplug** [comment] 2024-07-19 11:43
Once again another addon had been mentioned in an issue so I'll be closing this issue. People will never learn.

**Comment by umbrellaplug** [comment] 2024-08-02 15:14
@alexp4re Would you be able to test a possible fix for this?

**Comment by alexp4re** [comment] 2024-08-02 20:02
> @alexp4re Would you be able to test a possible fix for this?

yes, anything you need. i will try on my end. just give me detailed instructions.

**Comment by umbrellaplug** [comment] 2024-08-02 20:13
Can you try downloading the latest test version of umbrella from the repo here:
https://umbrellakodi.github.io

Once you have the latest version, try setting your default play action in kodi to "show information" instead of play and see if you still have the issues you were having before.

**Comment by adamosborne83** [comment] 2024-08-02 20:22
> > @alexp4re Would you be able to test a possible fix for this?
> 
> yes, anything you need. i will try on my end. just give me detailed instructions.

Just expanding on what UD has mentioned, you can do Show Info on kodi settings, but also, try it with play next also enabled in Umbrella settings. 
To test the play next feature, May I suggest Time Remaining, I set mine to 120 seconds, that way I could test it. Looking forward to your replies.

**Comment by alexp4re** [comment] 2024-08-02 21:10
> Can you try downloading the latest test version of umbrella from the repo here: https://umbrellakodi.github.io
> 
> Once you have the latest version, try setting your default play action in kodi to "show information" instead of play and see if you still have the issues you were having before.

same issue with latest umbrella update. will wait for further instructions.

**Comment by adamosborne83** [comment] 2024-08-02 21:24
> > Can you try downloading the latest test version of umbrella from the repo here: https://umbrellakodi.github.io
> > 
> > Once you have the latest version, try setting your default play action in kodi to "show information" instead of play and see if you still have the issues you were having before.
> 
> same issue with latest umbrella update. will wait for further instructions.

UD will want to see a log is possible.

Now, if you can test a theory I have, if not too much effort, can you try on a brand new kodi install?

**Comment by umbrellaplug** [comment] 2024-08-02 21:24
Can you please turn on logging within the addon, try it again, use the addon to post the log to paste in, then post a link here so I can review what's happening and if the fix is being applied.

**Comment by alexp4re** [comment] 2024-08-02 22:13
> Can you please turn on logging within the addon, try it again, use the addon to post the log to paste in, then post a link here so I can review what's happening and if the fix is being applied.

i will try. it will take some time since i never upload log before. fyi, latest update broke source select settings for tv shows.

on a different note i am helping @adamosborne83 test out playnext, the latest umbrella update will not save my settings for tv shows for source select. i mean it does, but once i play the media, it reverts back to autoplay in settings. i am encountering playnext will jump an entire season. with deafault action to INFO, to be honest, playnext have never worked properly for me. sometimes it works & other times it doesn't even pop up and other times it pops up a few seconds before media ends.

@adamosborne83 - after testing playnext for about an hour, i think playing the tv show  with default action "show info" & playing tv shows via context menu "play only this" is screwing up the playnext feature. sometimes playnext pops up & most times it doesn't. it will also jump an entire season too. playnext seems to work fine as long as the kodi settings is set to play, instead of "info". keep in mind that i am testing this out on the latest umbrella version today with UD.

**Comment by alexp4re** [comment] 2024-08-02 22:29
> Can you please turn on logging within the addon, try it again, use the addon to post the log to paste in, then post a link here so I can review what's happening and if the fix is being applied?

not sure if i done it correctly. but here it is below.
https://paste.kodi.tv/abugekeqid

**Comment by umbrellaplug** [comment] 2024-08-05 15:31
Thank you for trying that. I apologize for the delay in getting a response I was unable to get to a computer this weekend. I have looked over the logs and duplicated another user's setup here. I have made some changes this morning to the code. Can you please try version 6.6.648 from the test repo and let me know your results?

**Comment by alexp4re** [comment] 2024-08-05 21:11
> Thank you for trying that. I apologize for the delay in getting a response I was unable to get to a computer this weekend. I have looked over the logs and duplicated another user's setup here. I have made some changes this morning to the code. Can you please try version 6.6.648 from the test repo and let me know your results?

hi UD - the version that came up on the repo is umbrella 6.6.650, not v6.6.648. after testing it out i came to this conclusion.
1. in settings for tv shows, source selects still reverts back to autoplay.
2. i can see the hour glass when i select play where it's resolving to find a source, where as before there were no confirmation/signs of anything.
3. with your latest revisions, i can confirm that play does work(YEAH!), but after atleast many tries between roughly 5-8 tries.  it's not consistent on the first try.

will wait for further instructions.

**Comment by umbrellaplug** [comment] 2024-08-05 21:15
> in settings for tv shows, source selects still reverts back to autoplay.
The settings for TV Shows will automatically go back to auto play any time you have continuous playback turned on. If you want the setting for source select to stick turn off continuous playback. It actually tells you this in the settings when you select that setting.

> i can see the hour glass when i select play where it's resolving to find a source, where as before there were no confirmation/signs of anything.

what?

> with your latest revisions, i can confirm that play does work(YEAH!), but after atleast many tries between roughly 5-8 tries. it's not consistent on the first try.

i'm sorry, what?

**Comment by alexp4re** [comment] 2024-08-05 21:23
with your latest revisions, i can confirm that play does work(YEAH!), but after atleast many tries between roughly 5-8 tries. it's not consistent on the first try.

i'm sorry, what?

i don't know how to say it any other ways, but play will work but not on first try. it may take atleast 5-8 tries. it's progress for you. we know it works but not at first try. hope you understand what i mean.

**Comment by umbrellaplug** [comment] 2024-08-05 21:28
> with your latest revisions, i can confirm that play does work(YEAH!), but after atleast many tries between roughly 5-8 tries. it's not consistent on the first try.
> 
> i'm sorry, what?
> 
> i don't know how to say it any other ways, but play will work but not on first try. it may take atleast 5-8 tries. it's progress for you. we know it works but not at first try. hope you understand what i mean.

Can you post a log?

**Comment by alexp4re** [comment] 2024-08-05 21:34
UD - i disabled playnext & it works perfectly. i'm so happy now. i had trouble when playnext was enabled which i stated earlier where it may take clicking play over 5-8 times before it played.

**Comment by umbrellaplug** [comment] 2024-08-05 21:35
Cool. Would like to keep playnext working as well. Can you post a log so I can see what was happening with playnext enabled that prevented you from playing?

**Comment by alexp4re** [comment] 2024-08-05 22:44
> Cool. Would like to keep playnext working as well. Can you post a log so I can see what was happening with playnext enabled that prevented you from playing?

sorry for delay. i was still testing things out . as i try to reproduce the errors before upload the debug log for you, i can confirm that the playnext works 90% (rough estimate) of the time now. i think the reboot to kodi straighten things out. i encountered a few shows(the office, S1E1,S3E1,S4E1)) where i had to click play many times for it to work, but overall i say it's working so far. icthink somehow the autoplay is resolving to find a good source but the selection it chose failed to play. maybe there's something you can do on your end? just in case i forget, i want to thank you for you continual great work for umbrella. you made my day.

if you still want to see why those episodes are not playing on the first try & you like a debug log then i need to know how to bypass the 1mb limit upload error.

**Comment by alexp4re** [comment] 2024-08-05 23:07
on another note, do you know why my context menu in umbrella isn't working properly? items that i disable like play trailer & trakt manager are showing up in context menu and items that i enabled like play from here, auto play, & source select are not showing up in the context menu. i have tried to disable other context menu addon that may conflict, but it's the same problem. is there something i am missing? any suggestions? thanks.

**Comment by umbrellaplug** [comment] 2024-08-05 23:34
> if you still want to see why those episodes are not playing on the first try & you like a debug log then i need to know how to bypass the 1mb limit upload error.

i'm not sure how to bypass that limit. if you restart kodi it creates a fresh log. Can you clear all cache from the addon options by going to Umbrella > Tools > Clear all cache

You will get a warning, just click ok.

Once you do that can you please try one of your shows giving you issues and as soon as you have an issue where you need to retry a link more than once, upload the log at that point so it isn't as large of a file size. I'm not sure what would be causing your context menu items to act that way. In my testing here, context menu hide and show is working as expected. Please keep in mind the context menu from a widget and context menu from within the addon would be different and hiding and showing things in the context menu would not work once within the addon because it's building the context menu on each item. It's really difficult to tell the issue based on just a description, everyone hates to hear this but we really need the logs to see what's happening.

**Comment by alexp4re** [comment] 2024-08-06 00:12
hi UD - i came here to report that playnext does not popup & it does not play even though playnext default action set as "play" in settings. i even disable upnext addon just to make sure there's no conflict.

as i am still double checking if the autoplay works consistently, i have to say no. somehow as it resolve to find a reliable source to play the selection failed. currently, this is not fixed to push out a stable version.

**Comment by alexp4re** [comment] 2024-08-06 00:26
here's the log for your review.
https://paste.kodi.tv/awidomezuy

**Comment by umbrellaplug** [comment] 2024-08-06 12:10
awesome! thanks for the logs. your logs show I have some type of error in my "build season playlist" function. I will look into this, but do you mind unchecking the setting in Umbrella > Settings> TV Shows > Continuous Episode Playback Settings > Continue to next season (if available) and make sure that is unchecked. After unchecking that setting, can you let me know if you're still having the playback difficulty? I think we're getting pretty close to a fix here, but I want to make sure it's working as expected before pushing to the public.

from feedback from testing this I have also made some changes to use subtitle time for playnext setting as well and it should also be working better. There were situations where when open subs didn't return subs for a show it would just continue to try to download the subs over and over instead of using your fallback time and that was causing the playnext window to not show up.

**Comment by alexp4re** [comment] 2024-08-06 18:38
hi UD - i unchecked it & here are the results. most of the time it doesn't works, but sometimes it may. i'm so confused. it's not consistent. i would provide a log, but i am unable to with the 1mb limit upload error. i reproduce actions with a few limited tries, but hit with the 1mb error already. my attempt failed. not sure i can send you logs in the future, but i will try.  i add a pic attached if it may help. i will wait for further instructions from you.
![SNAG-0000](https://github.com/user-attachments/assets/682cbdde-5abd-4269-b7b4-ec791ac1e537)

**Comment by alexp4re** [comment] 2024-08-06 21:17
hey UD - a single watched tv episode in watch trakt history shows twice in  about 3 minutes apart from one another. this problem started last saturday. it has never happen before with umbrella. it does work fine for other video addon. maybe umbrella marlks it watch at the 85% setting in umbrella then trakt marks it watch after episode is done. i'm just guessing. i just want to bring it to your attention whatever you do with it.

i hope it's ok to bring umbrella issues up to you if run across them.

also, since we are on this topic matter, movies/tv shows that we add to trakt watchlist in umbrella are taking hours/within a day to show up whereas other video addon it appears instantly. not sure if there's something you can do on your end to improve it, because this feature is very important to me that i have resort to another addon to use this feature.

**Comment by umbrellaplug** [comment] 2024-08-07 03:25
> hey UD - a single watched tv episode in watch trakt history shows twice in about 3 minutes apart from one another. this problem started last saturday. it has never happen before with umbrella. it does work fine for other video addon. maybe umbrella marlks it watch at the 85% setting in umbrella then trakt marks it watch after episode is done. i'm just guessing. i just want to bring it to your attention whatever you do with it.
> 
> i hope it's ok to bring umbrella issues up to you if run across them.
> 
> also, since we are on this topic matter, movies/tv shows that we add to trakt watchlist in umbrella are taking hours/within a day to show up whereas other video addon it appears instantly. not sure if there's something you can do on your end to improve it, because this feature is very important to me that i have resort to another addon to use this feature.

if you are running the addon and trakt addon you need to use one or the other to scrobble. When the trakt addon and umbrella are both set to scrobble you will have issues like that. Movies and TV shows cache time can be adjusted in the cache settings. They should update when trakt syncs. I will be making some changes to the code and how playlists are built. I will let you know when a test version is available with those changes.

**Comment by umbrellaplug** [comment] 2024-08-08 21:24
Can you please try the latest version of umbrella on the test repo (6.6.654) and please go to Kodi > Settings > Videos > Play next video automatically and make sure nothing is selected? It's likely set to episodes now.

**Comment by alexp4re** [comment] 2024-08-09 01:17
hi UD - with the recent update, i feel it has improved playing the tv show, but still struggle to find a working source in a decent  timely fashion. sometimes it works. link to log below. it should showed it failed the first two tries then work on the third try. hopefully it will help you.

playnext sometimes work. sometimes it pops up & other times it didn't. if it did popup & i click play now, the image on screen freezes about 15 seconds then sometimes it works & other times it didn't. it's not consistent.

i want you to know that my kodi has always been buggy. my kodi suffers from regular freezes, random crashes, freeze on exit of kodi & major video glitches/tear. i would start kodi over from scratch, but it would take so much work to get it back where it is now, which i want to avoid. i'm not sure i am the ideal candidate to test for you. i will if you still need me to, but keep what i said in mind.

https://paste.kodi.tv/abofiyecer

**Comment by kodifitzwell** [comment] 2024-08-09 05:12
these are errors from RD when you are trying to stream:

    2024-08-08 17:31:05.297 T:10236   error <general>: CCurlFile::XFILE::CCurlFile::Open - <https://lax5-4.download.real-debrid.com...
    2024-08-08 17:31:05.297 T:10236   error <general>: CFileCache::XFILE::CFileCache::Open - <https://lax5-4.download.real-debrid.com...
    2024-08-08 17:31:26.505 T:17312   error <general>: CCurlFile::XFILE::CCurlFile::Open - <https://lax1-4.download.real-debrid.com...
    2024-08-08 17:31:31.592 T:17312   error <general>: CCurlFile::XFILE::CCurlFile::Open - <https://lax1-4.download.real-debrid.com...
    2024-08-08 17:31:31.592 T:17312   error <general>: CFileCache::XFILE::CFileCache::Open - <https://lax1-4.download.real-debrid.com...
    2024-08-08 17:31:58.413 T:14496   error <general>: CCurlFile::XFILE::CCurlFile::Open - <https://lax4-4.download.real-debrid.com...
    2024-08-08 17:32:20.901 T:7220    error <general>: CCurlFile::XFILE::CCurlFile::Stat - <https://lax4-4.download.real-debrid.com...

this is definitely a RD issue.  I am having the same 503 errors and spotty playback starting at about the same time this evening from the LAX server too.  good to know it's not just me.

same show too, HOTD, The Boys, and a few others.

umbrellaplug has been helping me with some PlayNext code over the past few days and I've been doing a lot of testing.  I was starting to think RD was limiting me for all the start/stops/resolve/adding links.

once I switched to my back up (Offcloud), no errors.

I would say give it a rest until tomorrow hopefully RD patches things up at LAX.

**Comment by alexp4re** [comment] 2024-08-09 23:39
hi UD - after further testing today, i can say it is working well overall. i'm not sure if you did anything on your side from the last testing from yesterday i sent you results. yesterday it's resolving & struggle to find a good source to play the tv show, but today it doesn't. everything plays in reasonable amount of time & it doesn't struggle to play source.

playnext is also working well. it popup when it should & it works consistently now. yesterday it took about 15 seconds while "video screen image frozen" until it struggle to play the next episode. now it took about 5 seconds; a reasonable amount of time to find the next playable source link for next episode. from the time you click "play now", it's the frozen image on the video screen while you wait that's off putting. if you could improve this part then it will be great. this is just nit picking.

would like to hear your feedback. -alex

umbrella v6.6.655

**Closed** 2024-08-21 15:40 UTC
Labels: bug
