### ISSUE TITLE
No Umbrella Icon when scraping for links

### ISSUE THREAD

**Issue by DROIDshield** [umbrellaplug/umbrellaplug.github.io#193] opened 2023-01-13 02:33 UTC
### Feature

Umbrella is the only addon I can think of who has nearly gifted me what I've always wanted  but stopped short. When scraping for links your options are foreground, back ground and now Icon only. 

Is it possible to have the icon switched off so it's just searching blind but if there aren't any links it will just say no links found?

For years I've been try to have that really authentic look but when using foreground,  background or even icon which I might add is much better but I'd love it if the option was there to switch the icon off so I just click play and a few seconds later it plays... what do you think?

### Is this feature available already in another plugin?

No none that I know of this would make this addon unique.

**Comment by umbrellaplug** [comment] 2023-01-13 02:41
For every one of you there's 900 

"it's not scraping because I can't see anything"

I honestly don't mind doing it but I'm terrified of the backlash of stupidity on this one. Second time this request has come in. The "icon only" was my first compromise on this request. Let me think if there's a way to do this that might work.

Being unique isn't tempting for me. 😀

**Comment by DROIDshield** [comment] 2023-01-13 09:33
I hear you and understand but my request is a case of every other addon I can think of allows only for foreground or back ground.  You are unique in offering just the umbrella and I applaud you for doing this.. but if the same bit of code could be added where it just doesn't reach for the icon but doe's exactly the said... not only will this be totally bad ass.. but the beast and most updated addon with a top of the range settings... you know this is a great idea right??? 😊🍾🥂

**Comment by umbrellaplug** [comment] 2023-01-15 15:08
What about resolving screen? When you scrape it goes through 2 screens. Scraping then Resolving. Are you wanting both of these blank?

**Comment by DROIDshield** [comment] 2023-01-16 00:30
Resolving and Scraping screens for me are already blank. Because I am using icon only and the Scraper Dialogue Highlight Color is set to black no text is shown apart from please wait. This flashes up for a second twice then I get the umbrella count round clockwise then the film or TV programme will start or say no links found. This is using skin AH2

When I try your addon alone with Kodi, again there is no text when scraping and resolving using icon only setting and black text. Just the icon counting clockwise to start.

So for me all i need is for the umbrella to not show, but if you have a way to remove the please wait to, then that would be a added bonus. Thanks for still thinking about this feature.

**Comment by DROIDshield** [comment] 2023-01-16 00:31
![20230116_001339](https://user-images.githubusercontent.com/97023369/212575944-8e8801f7-cdce-4909-b4c9-47e3bc3d68f9.jpg)

**Comment by cboRD181** [comment] 2023-02-02 23:57
> For every one of you there's 900
> 
> "it's not scraping because I can't see anything"
> 
> I honestly don't mind doing it but I'm terrified of the backlash of stupidity on this one. Second time this request has come in. The "icon only" was my first compromise on this request. Let me think if there's a way to do this that might work.
> 
> Being unique isn't tempting for me. 😀

I'm content with the umbrella icon, but if you do implement a fully background scrape & resolve for autoplay, couldn't you include a small "No links found" message in the event that the scrape doesn't return results? I'd imagine this would keep users from being confused into thinking the addon wasn't doing anything while processing in the background, but you obviously have more experience with user feedback, so correct me if I'm wrong. 

This way it either "just works" or the no links message gives the user assurance that the problem is not one with umbrella.

**Comment by umbrellaplug** [comment] 2023-02-03 00:07
I'm going to implement this in the next update as a blind scrape option.

**Comment by cboRD181** [comment] 2023-02-03 00:12
> 

look forward to seeing it! thanks for the quick response and receptivity to suggestions, as always

**Comment by DROIDshield** [comment] 2023-02-03 11:31
Oh wow... nice one can't wait...

**Comment by umbrellaplug** [comment] 2023-02-07 23:21
in update 6.6.13

**Closed by umbrellaplug** 2023-02-07 23:21 UTC
Labels: feature, awaiting results

**Comment by DROIDshield** [comment] 2023-02-08 13:30
Works, fantastic 👏 👌 👍 😀
