### ISSUE TITLE
[BUG] resolving popup window formating

### ISSUE THREAD

**Issue by saxoloman** [umbrellaplug/umbrellaplug.github.io#315] opened 2023-08-15 08:38 UTC
### Bug

When selecting link for movie or tv show there is little popup with link selected and movie poster.
They look very wrong on my end.image is stretched out and filename is badly placed.

### Expected Result

For poster image to not be streched
And filename to be centered

### Steps To Reproduce

Play movie
Select link
Look at the popup 

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

Coreelec 20.3 latest nightly
AH2 skin
![IMG_20230815_102051](https://github.com/umbrellaplug/umbrellaplug.github.io/assets/99698419/5a71df54-bd8b-433b-895f-46fe3710a138)

Kodi log

https://paste.kodi.tv/tabizopame

Umbrela log with debuging didnt show anything

This started happening as soon as you introduced this feature i just didnt want to bother you with it at the time.

### Checklist

- [X] I have included logs and the version of Kodi I am using..
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by 666jones** [comment] 2023-08-15 08:57
You could try going into umbrella settings - general - use custom umbrella dialogues - unselect this. And if you want it to be full screen you can go into umbrella - settings - source options - progress dialog (scraping and resolving) and select fullscreen or hide it completely. You can also choose to include artwork for background. Full screen with umbrella dialogs turned off with artwork as background will look like this.
![20230815_095630](https://github.com/umbrellaplug/umbrellaplug.github.io/assets/121204283/9b0a4a3e-a469-4ee5-a747-ffa3011d729e)

**Comment by saxoloman** [comment] 2023-08-15 11:30
@666jones 
Thats one way around it,this completely eliminates my issue.
Thank you

**Comment by umbrellaplug** [comment] 2023-08-15 11:48
That's not a bug. You just don't like how it looks.

Insulting my work. SMH

I'll change the art size. I was using the same size as the qr code images because it was less code to stuff either image into the same size box but I can adjust that. 

The text is just whatever the resolving link name is. Might change that to something else.

**Comment by saxoloman** [comment] 2023-08-15 12:18
Im sorry,but it does look like a bug. I didnt mean to insult you i have big respect for your work even if it looks hideous 🤫

**Closed** 2023-08-15 12:19 UTC
Labels: bug

**Comment by adamosborne83** [comment] 2023-08-15 12:44
> Im sorry,but it does look like a bug. I didnt mean to insult you i have big respect for your work even if it looks hideous 🤫

Please Umbrella, sort this. The last line alone makes it worth while LMFAO

**Comment by umbrellaplug** [comment] 2023-08-23 20:55
![image](https://github.com/umbrellaplug/umbrellaplug.github.io/assets/107957815/12220a0f-c3e3-46bd-8089-4b253f0b4445)

Since you both shit talked the way it looked before. here's how it looks in the update.

**Comment by adamosborne83** [comment] 2023-08-24 05:12
> Since you both shit talked the way it looked before. **Edited to remove picture***
> Try the latest test version and see if it's still hideous. lmao

Looks really good..... who did it?

**Comment by saxoloman** [comment] 2023-08-24 11:10
> Since you both shit talked the way it looked before. **Edited to remove picture*** Try the latest test version and see if it's still hideous. lmao

This is the way.
Thank you very much,it looks perfect now .
