### ISSUE TITLE
Keeps Crashing.....

### ISSUE THREAD

**Issue by adamosborne83** [umbrellaplug/umbrellaplug.github.io#7] opened 2022-07-02 14:00 UTC
https://paste.kodi.tv/oqijesogul

Curious, where did you fork venom from? Just I found out today, that if forked from somewhere I particular there is a code in it, that could be causing an issue....

**Comment by adamosborne83** [comment] 2022-07-02 14:18
![IMG_20220702_151619_288](https://user-images.githubusercontent.com/78307374/177004623-7ac13e87-544b-4452-be70-2802b579edc1.jpg)
![IMG_20220702_151708_907](https://user-images.githubusercontent.com/78307374/177004626-bf6e927f-7bbb-4003-a94e-d269988aec7d.jpg)
![IMG_20220702_151730_689](https://user-images.githubusercontent.com/78307374/177004628-0a8b5680-c033-4265-9d80-58cabdcfbbac.jpg)

**Comment by umbrellaplug** [comment] 2022-07-02 15:19
I've been wondering about my libraries used if it might have been an issue with the requests module being used in python. I bet this is an issue.  I'm wonder if this is probably the source of #2 Issue also.

My original files came from a download of the last zip file venom posted before he washed his hands of it. I wasn't able to get a true fork before venom came down. The package I used was 6.5.6

**Comment by adamosborne83** [comment] 2022-07-02 15:25
> I've been wondering about my libraries used if it might have been an issue with the requests module being used in python. I bet this is an issue. I'm wonder if this is probably the source of #2 Issue also.
> 
> My original files came from a download of the last zip file venom posted before he washed his hands of it. I wasn't able to get a true fork before venom came down. The package I used was 6.5.6

I'm in a telegraph channel and asking questions now, haha

**Comment by kodifitzwell** [comment] 2022-07-02 15:34
I believe code the OP is referencing is the scrapers pushed out after 2.1.8?  venom 6.5.6 is the last version I have archived as well.

in any case, is not requests a dependency that is download from official "kodi repository" at time of addon install?  not baked into venom/fen/kodi.

**Comment by umbrellaplug** [comment] 2022-07-02 15:53
I likely broke this yesterday with my custom timeout nonsense trying to troubleshoot an "Episode Not being Marked" issue. I'm checking it now. Watch for an update in the next few to fix this.

**Comment by adamosborne83** [comment] 2022-07-02 15:57
> I likely broke this yesterday with my custom timeout nonsense trying to troubleshoot an "Episode Not being Marked" issue. I'm checking it now. Watch for an update in the next few to fix this.

No worries, thank you and sorry to be a pain...

**Comment by adamosborne83** [comment] 2022-07-02 16:02
Here is another log, don't know if it will help or not....

But after I watch anything it crashes 

Https://paste.kodi.tv/disunoviwo

**Comment by umbrellaplug** [comment] 2022-07-02 16:36
> 

What about ezra or kingpin? Do you get an crashes or anything with those? Your requests module matches mine. What are you searching for? I'm wondering if there's a special character or something hitting the scraper. Are you doing it from tmdbhelper? Can you please give me steps to re-produce the issue. I have a windows kodi 19.4 environment and a kodi 19.3 android environment and my requests module in both matches yours. @kodifitzwell is correct in that the module is downloaded from kodi not the plugin. It's shared among all your plugins.

**Comment by adamosborne83** [comment] 2022-07-02 16:45
> > 
> 
> What about ezra or kingpin? Do you get an crashes or anything with those? Your requests module matches mine. What are you searching for? I'm wondering if there's a special character or something hitting the scraper. Are you doing it from tmdbhelper? Can you please give me steps to re-produce the issue. I have a windows kodi 19.4 environment and a kodi 19.3 android environment and my requests module in both matches yours. @kodifitzwell is correct in that the module is downloaded from kodi not the plugin. It's shared among all your plugins.

Hey, I do not use Ezra or Kingpin so I am not in a position to say,
I use a mix of library item for movies and point my widgets and my tv lists through umbrella.
This happens on both library movies and TV shows through umbrella directly. 

I am on a firecube using kodi 19.4.

**Comment by adamosborne83** [comment] 2022-07-02 16:46
So these crashes have happened on The Boys and Stranger things.

They are on my widgets coming from Trakt Trending within tv shows.

Skin I use us auramod

**Comment by adamosborne83** [comment] 2022-07-02 16:48
Another log haha.

Https://paste.kodi.tv/ujiregopoz

**Comment by Wilson-Fisk** [comment] 2022-07-02 16:55
> > > 
> > 
> > What about ezra or kingpin? Do you get an crashes or anything with those? Your requests module matches mine. What are you searching for? I'm wondering if there's a special character or something hitting the scraper. Are you doing it from tmdbhelper? Can you please give me steps to re-produce the issue. I have a windows kodi 19.4 environment and a kodi 19.3 android environment and my requests module in both matches yours. @kodifitzwell is correct in that the module is downloaded from kodi not the plugin. It's shared among all your plugins.
> 
> Hey, I do not use Ezra or Kingpin so I am not in a position to say,
> I use a mix of library item for movies and point my widgets and my tv lists through umbrella.
> This happens on both library movies and TV shows through umbrella directly. 
> 
> I am on a firecube using kodi 19.4.

If you could test kingpin, that would be a help to figure out if the thought issue is the issue or not

**Comment by umbrellaplug** [comment] 2022-07-02 17:03
@Wilson-Fisk is right. He's not just shamelessly promoting. :)

Umbrella and Kingpin are both based of the same venom clone. Umbrella has had a few changes in the past few days to try to track down a issue. If those changes are causing your issue, we will know real quickly if it doesn't happen in kingpin but does in Umbrella.

**Comment by adamosborne83** [comment] 2022-07-02 17:05
> @Wilson-Fisk is right. He's not just shamelessly promoting. :)
> 
> Umbrella and Kingpin are both based of the same venom clone. Umbrella has had a few changes in the past few days to try to track down a issue. If those changes are causing your issue, we will know real quickly if it doesn't happen in kingpin but does in Umbrella.

I am more than happy to try kingpin, but obviously that it will not work on movies in my library, as I used Umbrella for my movies and kingpin will be unable to read them.

**Comment by umbrellaplug** [comment] 2022-07-02 17:07
Is the crash occurring every time at the end of watching an epsiode?

**Comment by adamosborne83** [comment] 2022-07-02 17:10
> Is the crash occurring every time at the end of watching an epsiode?

Well it has just taken me 6 attempts to watch stranger things episode.... cleared cache, provider cache etc and still wasn't playing ball. Very peculiar. 
Fresh kodi install.
Auramod
Openwizard
Tmdbh
Umbrella. 

Not an over loaded set up either.

**Comment by adamosborne83** [comment] 2022-07-02 17:12
Spoke too soon 10 mins into an episode and crash.

10 crashes today so far haha

Another log


Https://paste.kodi.tv/ozuxuvohej

**Comment by adamosborne83** [comment] 2022-07-02 17:21
Kingpins seems OK at present, will report back after I try to watch next episode of stranger things

**Comment by umbrellaplug** [comment] 2022-07-02 18:03
Just pushed version 6.5.35 up. Let me know if that resolves your crashing issue. I removed custom timeout and logging statements.

**Comment by adamosborne83** [comment] 2022-07-02 18:13
> Just pushed version 6.5.35 up. Let me know if that resolves your crashing issue. I removed custom timeout and logging statements.

OK, will try it next. Thank you

**Comment by adamosborne83** [comment] 2022-07-02 18:37
Touch wood, seems as good, tried a couple episodes, no crash yet..... Will keep you updated haha.
Thank you to all,

**Comment by adamosborne83** [comment] 2022-07-02 18:54
Still crashed.....
Here is the log.....
Https://paste.kodi.tv/gudaradulo
Sorry

Guessing it's just me, so I'll go back onto old addon haha

**Comment by umbrellaplug** [comment] 2022-07-02 19:49
Try 6.5.36

**Comment by adamosborne83** [comment] 2022-07-02 19:51
> Try 6.5.36

Will do, my apologies if I am taking advantage of your generous nature with this addon..

**Comment by umbrellaplug** [comment] 2022-07-02 20:04
Nah, Crashing is an issue. I haven't been able to duplicate it though. I don't use widgets or anything though so I may not be doing this right. I also have Kodi 19.3 on my android not 19.4, but my windows build is running 19.4. I'm not seeing it there either. 

I'm going to try see if I can duplicate the issue. In the 6.5.36 build I removed all my logging. I suspected it was the connection parameter change on timeout causing your issue, but it doesn't look like that's the case as that's been removed and you're still crashing.

**Comment by adamosborne83** [comment] 2022-07-02 20:04
Https://paste.kodi.tv/limizivide

**Comment by adamosborne83** [comment] 2022-07-02 20:05
Https://paste.kodi.tv/eveculowot

**Comment by adamosborne83** [comment] 2022-07-02 20:11
> Nah, Crashing is an issue. I haven't been able to duplicate it though. I don't use widgets or anything though so I may not be doing this right. I also have Kodi 19.3 on my android not 19.4, but my windows build is running 19.4. I'm not seeing it there either.
> 
> I'm going to try see if I can duplicate the issue. In the 6.5.36 build I removed all my logging. I suspected it was the connection parameter change on timeout causing your issue, but it doesn't look like that's the case as that's been removed and you're still crashing.

Also, when inuse kingpin its fine, I was thinking maybe something got corrupted in kodi on the fresh install, but if kingpin is fine and does not crash I am guessing that it is not the issue.

**Comment by umbrellaplug** [comment] 2022-07-02 20:19
Yep, your issue is a fix I did for anime in the scrapers. Couple of minutes I'll have you fixed up.

**Comment by adamosborne83** [comment] 2022-07-02 20:22
> Yep, your issue is a fix I did for anime in the scrapers. Couple of minutes I'll have you fixed up.

Thank you 🙂 one thing I can promise, I will let you know either way haha

**Comment by umbrellaplug** [comment] 2022-07-02 20:38
Lol, I appreciate your patience. There was a fix I did in sources.py for $ in titles of shows and movies. I'd like to keep that in there, but you're getting an error from it. I am pushing a new version (yeah i know) 6.5.37 that should clean that up for you. Instead of removing the code I have put it in the try statement after checking for a none type. This SHOULD resolve your issue. and it actually was in plugin not scrapers. I haven't looked, but I'm pretty sure kingpin doesn't have this in it and may be the difference in the crashes.

**Comment by adamosborne83** [comment] 2022-07-02 20:43
> Lol, I appreciate your patience. There was a fix I did in sources.py for $ in titles of shows and movies. I'd like to keep that in there, but you're getting an error from it. I am pushing a new version (yeah i know) 6.5.37 that should clean that up for you. Instead of removing the code I have put it in the try statement after checking for a none type. This SHOULD resolve your issue. and it actually was in plugin not scrapers. I haven't looked, but I'm pretty sure kingpin doesn't have this in it and may be the difference in the crashes.

Haha bugger me, it's you who has the patience. I am just someone complaining about a free addon and your free time.
Looking forward to the update. Cheers again,

**Comment by umbrellaplug** [comment] 2022-07-02 20:54
Update pushed. Just compared. Kingpin does not have this "fix" lol.
@Wilson-Fisk If the crashing stops for him after this, you may want to look into this fix. It's to enable searching for titles with a "$" in the title. A lot of the time you don't get results for these because of the $ being a property value in so many languages that it just kinda makes the scrapers crumble. It's used all the time in anime titles though so I wanted to replace anyone searhing "Ca$h" with "Cash" when trying to get links.

**Comment by kodifitzwell** [comment] 2022-07-02 21:46
does everything get passed through ```cleantitle.py```?  maybe use ```title = title.replace('\$','s')``` there instead of ```sources.py```.

notice the **\\$** escapes the dollar sign.

**Comment by umbrellaplug** [comment] 2022-07-02 22:01
Yeah the titles are all checked in the source_utils.py. I think yes, we could probably put the title replace in clean titles module, but I was concerned about what else it might replace. So when I'm searching for movie... I need the $ for the title, but when I search for sources. I do not want the $ sign. That's why I put it in sources. Is that the best way to do it? I'm sure probably not... :)

**Comment by umbrellaplug** [comment] 2022-07-02 22:01
@adamosborne83 Has your crashing been resolved?

**Comment by umbrellaplug** [comment] 2022-07-02 22:03
> does everything get passed through `cleantitle.py`? maybe use `title = title.replace('\$','s')` there instead of `sources.py`.
> 
> notice the **\$** escapes the dollar sign.

I have noticed you around here and there. I didn't want you to think your plugin was being ignored. Is POV public? I notice you have a repo for zips, but no source up. If you would like I can add the info for plugin into my readme also. I'm all for options. I believe you forked the my account change also right?

**Comment by adamosborne83** [comment] 2022-07-02 22:12
> @adamosborne83 Has your crashing been resolved?

I am afraid not 

Kingpin still OK, as soon as I try umbrella it crashes. Here is log. 


Https://paste.kodi.tv/hapuxegema

**Comment by kodifitzwell** [comment] 2022-07-02 22:36
@umbrellaplug
it's all open source, all we have to do is download the zip and extract. lol  but yes it is public.

I actually moved on from myaccounts after all the renaming/versioning issues.  everything is authorized from my addon.  actually there were some things I had in my initial fork of myaccounts that I wanted to suggest to you/Ezra.  but I'm still learning git so I have to figure out the pull request.

in any case, I'm still learning git, never used it before.

the 3x I tried an announcement for my addon it was removed as "spam."  so mine is not well known, but I try to keep up with all the trakt error reports for Fen/Venom forks so I can try and reproduce/fix.

**Comment by umbrellaplug** [comment] 2022-07-02 23:09
@adamosborne83 
and here we go again. Can you please try 6.5.38? Removed the title change completely. Should match Kingpin now.

**Comment by kodifitzwell** [comment] 2022-07-02 23:23
@umbrellaplug 
and actually, scratch that comment about escaping $, I was thinking regex not python.

**Comment by umbrellaplug** [comment] 2022-07-02 23:49
I'm trying to follow his setup he had earlier. But I feel like I'm missing a bunch. I installed AuraMod and it has like 97 steps.... 

@adamosborne83 Can you give me the steps you take to create your widget your using to play videos? I have all the plugins and skins you mentioned earlier. I'm trying to duplicate the crash. I can't.

**Comment by Wilson-Fisk** [comment] 2022-07-03 00:11
> I'm trying to follow his setup he had earlier. But I feel like I'm missing a bunch. I installed AuraMod and it has like 97 steps.... 
> 
> @adamosborne83 Can you give me the steps you take to create your widget your using to play videos? I have all the plugins and skins you mentioned earlier. I'm trying to duplicate the crash. I can't.

If @adamosborne83 would want to, it might be easier to revoke all his auths and just zip the userdata and addon folders and send his whole setup. Auramod takes a lot of setting up, and has a ton of settings and sub settings through it.

Regardless, skins and widgets really shouldn't matter unless they are being run through tmdbhelper, which can cause other problems

**Comment by umbrellaplug** [comment] 2022-07-03 00:17
> > I'm trying to follow his setup he had earlier. But I feel like I'm missing a bunch. I installed AuraMod and it has like 97 steps....
> > @adamosborne83 Can you give me the steps you take to create your widget your using to play videos? I have all the plugins and skins you mentioned earlier. I'm trying to duplicate the crash. I can't.
> 
> If @adamosborne83 would want to, it might be easier to revoke all his auths and just zip the userdata and addon folders and send his whole setup. Auramod takes a lot of setting up, and has a ton of settings and sub settings through it.
> 
> Regardless, skins and widgets really shouldn't matter unless they are being run through tmdbhelper, which can cause other problems

TMDBHelper is a requirement of this skin. Along with a bunch of other nonsense. I'm digging the look, but all the nonsense that came with it is really looking ridiculous to me. I'm simple though. Im seeing a crazy amount of errors in my log now trying to follow his same exact path playing a video from the skin, using tmdbhelper, passing to umbrella as a player it hasn't crashed on me yet. but i also never did anything with the other addon he mentioned. "open wizard". 

lol, i'm also on the latest version I hadn't heard back from him yet on. I guess I might roll back to 6.5.37 with the title replace still in there and see if I can get it to crash then. I know my log looks a ton more like his now. just error after error.

**Comment by Wilson-Fisk** [comment] 2022-07-03 00:49
> TMDBHelper is a requirement of this skin. Along with a bunch of other nonsense. I'm digging the look, but all the nonsense that came with it is really looking ridiculous to me. I'm simple though. Im seeing a crazy amount of errors in my log now trying to follow his same exact path playing a video from the skin, using tmdbhelper, passing to umbrella as a player it hasn't crashed on me yet. but i also never did anything with the other addon he mentioned. "open wizard". 
> 
> lol, i'm also on the latest version I hadn't heard back from him yet on. I guess I might roll back to 6.5.37 with the title replace still in there and see if I can get it to crash then. I know my log looks a ton more like his now. just error after error.

Yea so quick just for the future, in cases like auramod, it's just a dependency, it pulls things like the artwork, and the info that the skin uses like the crew info, cast, some artwork, ratings, etc. Tmdbhelper really isn't a problem by itself, but can cause problems when used with it's player functions (usually doesn't cause much issue) or its library integration (which can definitely cause problems)

**Comment by umbrellaplug** [comment] 2022-07-03 00:56
@Wilson-Fisk Totally get it. He mentioned it earlier in his list of addons he had. I have installed where i needed to test and make sure my json files were working for it for the players section. I don't have the library integration turned on, I'm not sure if he does. I haven't messed with it much. I'm getting ready to try stranger things again with the title replace back in the code. (its only back in mine). Hopefully I can get it to crash so I can figure out the issue.

I haven't been able to reproduce it or had anyone else report it, so I'm starting to wonder if it's not related to his setup. That's the tough part with maintaining these plugins. Got to find the happy middle ground of being helpful vs wasting your time troubleshooting setup issues.

**Comment by adamosborne83** [comment] 2022-07-03 05:10
> @Wilson-Fisk Totally get it. He mentioned it earlier in his list of addons he had. I have installed where i needed to test and make sure my json files were working for it for the players section. I don't have the library integration turned on, I'm not sure if he does. I haven't messed with it much. I'm getting ready to try stranger things again with the title replace back in the code. (its only back in mine). Hopefully I can get it to crash so I can figure out the issue.
> 
> I haven't been able to reproduce it or had anyone else report it, so I'm starting to wonder if it's not related to his setup. That's the tough part with maintaining these plugins. Got to find the happy middle ground of being helpful vs wasting your time troubleshooting setup issues.

Apologies, it got to midnight and I passed out.
I donuse your library integration, but I did on venom too.
Nothing different whatsoever in set up.
I'm going to try a total clean install of kodi.

I'll report back later, thank you again

**Comment by adamosborne83** [comment] 2022-07-03 08:52
OK, total fresh installation.

This is the log, still crashes.
Kills me.....
Sorry think, I will have to give up.
Is odd though, as Venom worked fine and so did the fork of venom I previously used.
Gutted, as you seem engaged in helping. 

Https://paste.kodi.tv/vonasomaze

**Comment by adamosborne83** [comment] 2022-07-03 08:55
Odd behaviour is, that movies are fine, both library and through trending trakt. 

Only happens on TVShows

**Comment by adamosborne83** [comment] 2022-07-03 09:16
![20220703_101527](https://user-images.githubusercontent.com/78307374/177033257-dc584174-974c-4c3d-b681-1f5e762fae4d.jpg)
![20220703_101506](https://user-images.githubusercontent.com/78307374/177033258-806393ab-3b4d-4740-af48-71ccbce2b0d4.jpg)
![20220703_101445](https://user-images.githubusercontent.com/78307374/177033259-894dde98-277c-4ec7-80ae-7e9a7cc2ea57.jpg)

**Comment by umbrellaplug** [comment] 2022-07-03 15:03
If you're done messing with it I totally understand. I'd be annoyed as a user as well. If you feel like messing with it again I'm happy to keep looking into this.

You're version of umbrella should be almost identical to kingpin. The only difference would at this point would be icons, a clear cache function for icons and textures added, and the scrapers updated. Which leads me down the path of maybe it's a result I'm getting with my scrapers that's not coming in with kingpin. 

When it crashes, does it reboot the Kodi or is it just stopping playback and returning to home screen? On my android build I was able to get it to completely crash Kodi yesterday with "the boys" but it was due to the hvec video it was trying to play. 

What hardware are you using for this? I may try to get the same hardware to duplicate the issue here. 

Can you turn on debugging on Kodi and try a show that has crashed umbrella for you? If it does, grab log, play exact same show from kingpin then grab log again?

If your okay with trying a few more things let me know.

**Comment by adamosborne83** [comment] 2022-07-03 16:57
> If you're done messing with it I totally understand. I'd be annoyed as a user as well. If you feel like messing with it again I'm happy to keep looking into this.
> 
> You're version of umbrella should be almost identical to kingpin. The only difference would at this point would be icons, a clear cache function for icons and textures added, and the scrapers updated. Which leads me down the path of maybe it's a result I'm getting with my scrapers that's not coming in with kingpin.
> 
> When it crashes, does it reboot the Kodi or is it just stopping playback and returning to home screen? On my android build I was able to get it to completely crash Kodi yesterday with "the boys" but it was due to the hvec video it was trying to play.
> 
> What hardware are you using for this? I may try to get the same hardware to duplicate the issue here.
> 
> Can you turn on debugging on Kodi and try a show that has crashed umbrella for you? If it does, grab log, play exact same show from kingpin then grab log again?
> 
> If your okay with trying a few more things let me know.

Good Eve,
The only reason I'd stop, is to give you a break haha.... this is your time you're giving me for free.

I do not have it show dolby vision, as I am using a Samsung TV.

I use a 2nd Gen FireCube, which I have always got on fine with.

I will do what you have asked for.
I am not around as much this eve, so might be a bit more sporadic with logs etc.

Thank you again for your time.

**Comment by adamosborne83** [comment] 2022-07-03 17:19
Https://paste.kodi.tv/emekuduvuv

**Comment by adamosborne83** [comment] 2022-07-03 19:52
So it seems to be crashing when I get to the end of an episode or film.

Https://paste.kodi.tv/fupogobaye

**Comment by adamosborne83** [comment] 2022-07-03 20:58
Bloody typical,  seeing that I watched an entire episode with debugging on, it didn't crash.

Here is the log anyway......


Https://paste.kodi.tv/refiqosuho

**Comment by adamosborne83** [comment] 2022-07-03 21:04
So frustrated, I turn of debugging mode, as obviously the txt is annoying then 5 mins later crashes.......

Https://paste.kodi.tv/ikogereal

**Comment by umbrellaplug** [comment] 2022-07-03 21:58
Thank you, I'll keep looking over these and see if I can find anything,

**Comment by adamosborne83** [comment] 2022-07-04 05:52
> Thank you, I'll keep looking over these and see if I can find anything,

Fabulous, thanks for the effort.

**Comment by umbrellaplug** [comment] 2022-07-04 15:10
Can you turn on debugging in the settings of the scraper. Set to level to extra info and point it to kodi.log? Make sure scrapers and umbrella are set this way and you can leave debugging off in the actual kodi settings. So you don't get that crazy text overlay and all that but still will be doing debug logs for the two plugins.

**Comment by adamosborne83** [comment] 2022-07-04 16:13
> @adamosborne83 Can you turn on debugging in the settings of the scraper. Set to level to extra info and point it to kodi.log? Make sure scrapers and umbrella are set this way and you can leave debugging off in the actual kodi settings so you don't get that crazy text overlay and all that but still will be doing debug logs for the two plugins. I'm leaning more and more towards the scrapers. I'm also seeing some large amount of errors thrown into the debug logs. I'm also seeing errors from the log_utils for what it's actually trying to log as well. That would make more sense as to why your not seeing a crash in debug but you are in normal. It looks like one big pain to track down because scrapers are getting different results, sending some of those results to log_utility due to errors, log utility not able to log due to it not actually error catching itself and boom crash kodi.
> 
> Kingpin vs Umbrella = different scrapers = different results = different errors going to log utils.
> 
> Do you have your plugin set to auto-play next episode? NextUp enabled. I'm just trying to figure out if scrapers would be running in background during end of episode looking for next episode.

Hey, thanks for your reply.

I have done as you asked for with debug on scrappers.

Also, yes I do have next up to play in the app, and also, as suggested in kodi aswell.

Shall I disable this to see if that helps?
I'm only asking you, as you've got an idea what yo do, and I don't wanna mess with what you're thinking.

**Comment by umbrellaplug** [comment] 2022-07-04 17:34
Much better. Looks related to seeking. I'm still digging.

**Comment by adamosborne83** [comment] 2022-07-04 17:42
> Much better. Looks related to seeking. I'm still digging.

Thank you for being so persistent. I promise I'm not usually this high Maitenance

**Comment by umbrellaplug** [comment] 2022-07-05 01:31
@adamosborne83 Can you please change your plugin debugging settings to use the umbrella.log, myaccounts.log, and umbrellascrapers.log in the debug section of each plugin instead of kodi.log. I think the kodi log is making it harder to debug. I'm able to focus on this problem again as the my accounts issues have been worked out and would like to get this fixed.

**Comment by adamosborne83** [comment] 2022-07-05 08:30
Will do, I'll set it after work, then try and make it crash again.

**Comment by adamosborne83** [comment] 2022-07-05 16:03
![16570369652256887146123715226895](https://user-images.githubusercontent.com/78307374/177369882-1f4630bc-385c-4ada-b7e7-a7e5453e056a.jpg)
![Uploading 16570369859616224395509031279881.jpg…]()

**Comment by adamosborne83** [comment] 2022-07-05 16:04
Https://paste.kodi.tv/fasebenesi

**Comment by adamosborne83** [comment] 2022-07-05 16:04
Hope this helps

**Comment by adamosborne83** [comment] 2022-07-05 16:18
![16570378529256193780020035356283](https://user-images.githubusercontent.com/78307374/177372471-98cc0078-c52f-489a-a9ee-f10eb5c2109e.jpg)
![16570378853025772000365999955596](https://user-images.githubusercontent.com/78307374/177372518-a0b6e807-825d-4c02-b96c-39a68ae6d8f0.jpg)
![16570378997743236721728113518330](https://user-images.githubusercontent.com/78307374/177372537-a073268f-864a-41db-bb4e-c158ab1ea982.jpg)

**Comment by adamosborne83** [comment] 2022-07-06 18:59
Https://paste.kodi.tv/gijudohuqi

**Comment by adamosborne83** [comment] 2022-07-06 19:00
Https://paste.kodi.tv/fisuyufaki

**Comment by adamosborne83** [comment] 2022-07-06 19:02
![16571340785245001976340509647376](https://user-images.githubusercontent.com/78307374/177623627-1be59bb9-8ef1-42ba-b9a2-c6ad07ea52b2.jpg)
![16571340989895463658823757804418](https://user-images.githubusercontent.com/78307374/177623702-e98fca03-cea5-4205-988e-42da8a3625ec.jpg)

**Comment by umbrellaplug** [comment] 2022-07-06 19:02
Thanks. I'll Look over these after i finish this latest update. I got a few fixes coming and a nice little scraper update. Trying my best to get it done. Just wanted to also get another bug, but if it takes me much longer on this other bug I might just break them out into two different updates.

**Comment by adamosborne83** [comment] 2022-07-06 19:03
Https://paste.kodi.tv/yosakiteye

This is kodi log. FYI, not pestering with the logs, just more I send, the more help I thought it might be.

**Comment by umbrellaplug** [comment] 2022-07-06 19:04
No, it's no issue. Are you using your own TMDB api key? That doesn't look like mine.

**Comment by umbrellaplug** [comment] 2022-07-06 22:46
Okay, what all providers do you have enabled in in scrapers?

**Comment by adamosborne83** [comment] 2022-07-07 05:34
> Okay, what all providers do you have enabled in in scrapers? Do you get the crash with nextup and auto select for source turned off?

Scrappers are left at default.

I will turn off next up, and auto play later this eve.

I will do it both separately though to try with elimination.

**Comment by adamosborne83** [comment] 2022-07-07 16:22
> Okay, what all providers do you have enabled in in scrapers? Do you get the crash with nextup and auto select for source turned off?

So have done as requested.

Still got it to crash.
Here are the supported logs again, as I keep saying it only seems to be me... so do not worry too much.

![16572107366956871075496507262442](https://user-images.githubusercontent.com/78307374/177822369-fdaffe3f-10d8-414a-9eed-cca296249dee.jpg)
![16572107594773244291598194719552](https://user-images.githubusercontent.com/78307374/177822442-3aeb9b6d-6b5f-41b8-b748-c891f8c4f685.jpg)
![16572107785897700939080669574374](https://user-images.githubusercontent.com/78307374/177822498-0048fbf6-c858-4730-992d-62a0080424a7.jpg)
![16572107981805619788657341402329](https://user-images.githubusercontent.com/78307374/177822543-bef21ecb-77d4-4c73-a7e5-e3177604e812.jpg)



Scrappers log https://paste.kodi.tv/kaduwejewe

Kodi log https://paste.kodi.tv/oyegeviwiw

**Comment by umbrellaplug** [comment] 2022-07-07 17:10
Holy mother of errors......

yeah, looks like a proper "shit-ton" of errors from trakt lists that are private now. Working on something for this now. But I need to look over your logs to see what is causing the crash on you.

**Comment by adamosborne83** [comment] 2022-07-07 17:29
> You gave me kodi and scrapers log. Can you give me Umbrella log please? I had previously requested for you to isolate those from the kodi log so they aren't in there anymore. :) That's going to be where all those trakt errors are.

I only have the pictures for log.... i have set it up as you requested, but does not give me an option to upload a kodi.paste log as the others do.

See the pic of the settings.

**Comment by adamosborne83** [comment] 2022-07-07 17:30
![Uploading 16572150097564032312594659838855.jpg…]()

**Comment by umbrellaplug** [comment] 2022-07-07 19:19
Alright looking over this a couple of things. 
1. The file you are watching is a 9gb mkv. That seems large, but may not matter.

2. I need the logs from umbrella scrapers at the same time to make sure something was not going on there also.
`[2022-07-07 18:44:43] [2022-07-07 18:45:06] [2022-07-07 18:45:29]`
This appears to be the time period the crash happened. I'd like the logs from scrapers for that time period.

3. I would also like to know if kingpin is pulling the same file. 
Can you repeat the same steps for kingpin for the the debug log for the plugin try to watch the same show with settings for autoplay and such all set the same?

4. You have numerous trakt and tmdb errors. I'm working on the trakt errors, but I have not seen the tmdb errors. I'm going to add my own tmdb key into my accounts and see if I get the same thing.

**Comment by umbrellaplug** [comment] 2022-07-08 18:54
Can you reach out to me on reddit when you get a chance to do some troubleshooting? I've got some questions I'd rather not ask on github. :)

u/umbrella_dev

**Comment by adamosborne83** [comment] 2022-07-08 19:32
> Can you reach out to me on reddit when you get a chance to do some troubleshooting? I've got some questions I'd rather not ask on github. :)
> 
> u/umbrella_dev

Mammothbull frog....
I'll start a post on kodi addons, just saying umbrella venom addon, so you know it's me.

**Comment by adamosborne83** [comment] 2022-07-08 19:35
> 

Can't seem to find your user name. 
This is me 

https://www.reddit.com/u/Mammoth-Bullfrog-274?utm_medium=android_app&utm_source=share

**Comment by umbrellaplug** [comment] 2022-07-08 22:48
New package for scrapers is on repo now. Can you please download and test again. This should be fixed now.

**Comment by adamosborne83** [comment] 2022-07-09 06:24
> New package for scrapers is on repo now. Can you please download and test again. This should be fixed now.

It works.... thank you for persistence

**Closed** 2022-07-09 06:26 UTC
Labels: awaiting results
