### ISSUE TITLE
[BUG] "Direct Progress Scraping" + "Continuous Playback" skips one episode

### ISSUE THREAD

**Issue by OneAngryMan** [umbrellaplug/umbrellaplug.github.io#194] opened 2023-01-13 18:26 UTC
### Bug

Hi, 
I have set Umbrella's "Progress" menu as a widget on my home menu. When I activate Continuous Playback (PlayNext popup) and click on an item from that widget, I get taken to another menu with the remaining episodes of the season, from where I can play the episode and have the PlayNext popup take me to the next episode. I am trying to get rid of that extra menu (Autoplaylist Creation), so when I click on an item in that widget it directly plays the episode and the NextUp popup takes me to the next episode. Same way it works in Fen and Seren. The bug occurs with these settings:
Direct Progress Scraping = on
Continuous Playback/PlayNext popup = on
[Player -> Videos -> Play next video automatically = episodes]
[skin = ah2 v0.7.28(latest)]
[umbrella = v6.6.09(latest)]
What happens is that if I click on an item in my Progress widget, the PlayNext popup takes me to the episode after the next episode. So when I play episode 2 of some TV show, the PlayNext popup links to episode 4 instead of 3. If I don't interrupt the playback and just continue to watch more episodes using the PlayNext popup, then no more episodes get skipped. It's like the created playlist contains all remaining episodes of the season, with the exception of the "second" one. There also is no PlayNext popup at all when using the context menu action "Play from here". And if I navigate to the Progress Menu in Umbrella and play directly from there, the NextUp popup links to an episode from another TV Show (the one to the right in the menu).

The attached screenshots hopefully clarify the issue. This bug seems to be related to issue #29 which was closed as completed, so I am assuming the feature should be working(?) Somehow. If you are not able to reproduce the issue, I can upload a log file.

### Expected Result

Play the actual next episode instead of the one after.

### Steps To Reproduce

1. Turn "Continuous Playback"/"PlayNext popup" on
2. Turn "Direct Progress Scraping" on
3. (Set "Player" -> "Videos" -> "Play next video automatically" to episodes) 
4. (Use Arctic Horizon 2 as skin) 
5. Set "My TV Shows" -> "Progress" as widget on home menu
6. Play an episode from the widget and wait for the PlayNext popup.

### Logs, Screenshots, and Additional Info

![Screenshot (447)](https://user-images.githubusercontent.com/83606678/212388662-90cf7eae-afaa-460f-970b-ebb86f8800f9.png)
![Screenshot (448)](https://user-images.githubusercontent.com/83606678/212388672-8d809181-b5eb-4bee-8f08-8203f030ca6c.png)
![Screenshot (449)](https://user-images.githubusercontent.com/83606678/212388676-e1546126-bb8a-4f3e-acd2-9d7f3e428f2e.png)
![Screenshot (451)](https://user-images.githubusercontent.com/83606678/212388681-ed40e7a9-2a6b-4c60-a847-7a65244d7c8c.png)
![Screenshot (452)](https://user-images.githubusercontent.com/83606678/212388684-91c53377-f6f3-436e-8a1d-efbea1c06e30.png)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment] 2023-01-13 19:27
Okay. To confirm main issue you're having in short is one episode is being skipped each time a playlist is added? Just want to confirm I understand.

**Comment by umbrellaplug** [comment] 2023-01-13 20:54
> Pretty much, yes. Although I gotta say that with the whole interplay of skin, widgets, kodi settings, direct progress scraping, continuous playback, play from here etc it is kind of hard to understand what is actually happening. For example I have no idea why the PlayNext popup links to the episode after the next episode when playing from the widget vs linking to the episode of another show when playing directly from within the Progress submenu in Umbrella. I was hoping you could give me some insight into what's happening here.

Absolutely, so playnext works by using a playlist built each time you play a video. Where the playlist comes from is what's causing your issues here.

Kodi Settings come into play from some internal methods in Kodi where if the behavior for "Play next video automatically" is set to "Episodes" within Kodi Settings > Player >Videos, Kodi automatically creates a playlist from every video on a "list" or "directory" within kodi and starts playing the one you selected. A good example of this would be TV Show > Season 1 > Episode 1. Because we played this from the "episodes" list or directory the whole list of episodes in that season would be added to the playlist.

Continuous Playback looks at if you have the settings turned on and a playlist. It then uses the playlist to prescrape for the next item and play it when you hit a certain point in the video which is what I call the popup window "Playnext" that pops up towards the end of a video asking if you want to play, stop or whatever. There's also an addon called "UpNext" that can confuse people sometimes as well. If I'm being honest I would remove playnext because of how many issues I get in relation to it, but it's a loved feature so I leave it alone.

Direct Scrape - Uses your progress list to scrape for the next item on the list instead of the next episode of a show. That's when you'll see the jumping from one show to another and typically, playnext does not play well with that, but I really need to try it more. I use Umbrella and I use playnext some, but I don't use progress much or direct scrape so I'm not 100% sure what issue it might cause. I need to mess with this and see more details about the code and how it works because I get a lot of "issues" related to it.

Skins - Your issue you referenced originally #29 was due to a playlist not being created when an item was launched from a widget. This happened because as I previously mentioned above there's some "auto-magic" done when launching an episode from a list or directory. A widget is on the home screen so no directory of items when it's launched from widget to build a playlist for all this from. On #29 I wrote in a backup method where if launched from a widget it builds the playlist. This is likely the cause of your other issue. I probably have some issue in that code causing the episode skip... I will need to look.

**Comment by umbrellaplug** [comment] 2023-01-15 14:53
Found the issue. Next update will have a fix for this issue in particular. Direct progress scraping will still behave the same though. If you have direct progress scraping on and launch from a widget it's still going to find the next episode of the show you watched, not the next show in progress. If you launch from the progress directory inside Umbrella with the direct progress scraping enabled it will work that way though.

This fixes the skipped episode.

**Comment by umbrellaplug** [comment] 2023-01-15 17:37
You are correct. The same fix will account for that as well. The playlist (described before) was being cleared by another function in the process of completing the build playlist function causing the numbers to get out of order. It will be in 6.6.10 once it's pushed.

**Comment by umbrellaplug** [comment] 2023-01-21 22:09
in update 6.6.10

**Closed by umbrellaplug** 2023-01-21 22:09 UTC
Labels: bug, awaiting results
